spring:
  datasource:
    #TODO: replace the below url with the url where we would be keeping our schema. later moving it to a env file id p
    url: jdbc:postgresql****

  #JPA settings
  jpa.hibernate.ddl_auto: update

  #TODO add username and password below before doing dev work
  mail:
    host: smtp.gmail.com
    port: 587
    username: abc@gmail.com
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true